apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniurl-deploy
  labels:
    app: miniurl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miniurl
  template:
    metadata:
      labels:
        app: miniurl
    spec:
      containers:
        - name: my-miniurl
          image: leolas95/miniurl:14
          ports:
            - containerPort: 80